name: image_picker_web
description: Flutter Web Plugin to pick Images (as Widget, File or Uint8List)
  and Videos (as File or Uint8List)
version: 2.1.0
repository: https://github.com/Ahmadre/image_picker_web

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ImagePickerWeb
        fileName: image_picker_web.dart

