name: image_picker_web_redux
description: Flutter Web Plugin to pick Images (as Widget, File or Uint8List)
  and Videos (as File or Uint8List)
version: 1.1.2+1
homepage: https://github.com/TesteurManiak
repository: https://github.com/TesteurManiak/image_picker_web_redux

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0+1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ImagePickerWeb
        fileName: image_picker_web_redux.dart

