name: image_picker_web
description: Flutter Web Plugin to pick Images (as Widget, File or Uint8List)
  and Videos (as File or Uint8List)
version: 4.0.0
repository: https://github.com/Ahmadre/image_picker_web

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0

dev_dependencies:
  custom_lint: ^0.5.0
  fd_lints: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: ImagePickerWeb
        fileName: image_picker_web.dart
