name: Flutter Web CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1.5.3
    - run: flutter pub get
    - run: dart format --set-exit-if-changed .
    - name: Analyze project source
      run: flutter analyze
      working-directory: ./lib
    - name: Build example
      run: flutter build web
      working-directory: example

